### ISSUE TITLE
2d cylinder case, based on Openfoam

### ISSUE THREAD

**Issue by llyscj** [unicfdlab/libAcoustics#16]
Hi， I have already compiled the libAcoustics in Openfoam4.1,  is it  able to get the far field sound of  2d cylinder case? if not, what if the 2d flow field data is utilized in libacoustics by assuming that the loading does not vary in the direction of the length of the cylinder. then the 3d data can be got based on the 2d flow field.
In order to get the reasonable sound，can  someone help me modify the case？ the case is attached here.
[2dcylinder.tar.gz](https://github.com/unicfdlab/libAcoustics/files/3668888/2dcylinder.tar.gz)

**Comment by unicfdlab** [comment]
Hi,
first of all - we do not support older versions of OpenFOAM. The latest version of OpenFOAM we use is OpenFOAM+ v.1812.

Second, the libAcoustics library is intended primarily for 3D simulations, since acoustic analogies are usually applied to 3D hydrodynamic fields. The 2D cases are provided for educational purposes only.
