### ISSUE TITLE
"fixedResponseDelay" in file 'fwhControl'

### ISSUE THREAD

**Issue by lianjieyu** [unicfdlab/libAcoustics#48]
Dear author,
I have some question about the parameter "fixedResponseDelay" in file 'fwhControl'. Could you help me? I wonder if the "fixedResponseDealy" corresponds to the "time delay" in some literature (see for example https://doi.org/10.1016/j.jsv.2019.04.001)? Besides, I find that changing  the value of "responseDelay" seems to make no difference to the time history except to  the shift of the "fixedValue". Then what is the significance of setting this parameter? Finally, I noticed that the result becomes unreasonable when the value of "responseDelay" is negative. Could you help me to explain it?

**Comment by unicfdlab** [comment]
Hi
When fixedResponseDelay==true, the library doesn't account for time needed by acoustic wave to travel from a source to an observer. I.e., it is assumed that pressure disturbance emitted by FWH surface monopole/dipole reaches the observer after given in *responseDelay* time. In this case, only the delay associated with the characteristic length of FWH surface is applied.

It is especially convenient when the distance between observer and source is very large. Because you don't need to run calculation for the whole time the wave is travelling.

**Comment by lianjieyu** [comment]
Thank you very much for your help! I think I have understood your meanings.  

Furthermore, does the "travel time" fixed at the displace value from the compact point to the observer or various displace values depending on the surface mesh unit of the porous surface? In other words, I wonder if the difference of the time history of acoustic pressurefor is just a time shift, without any other difference for "fixedResponseDelay==true" and "fixedResponseDelay==false" respectively?

Waiting for your reply.

**Comment by unicfdlab** [comment]
![Untitled 1](https://user-images.githubusercontent.com/13945073/110588888-b0fe7900-8186-11eb-9992-629b471b7707.png)

Hi, responseDelay means that we substitute  the  minimum delay between source and observer with some value. Response delay is activated when  "fixedResponseDelay==true"

**Comment by lianjieyu** [comment]
Oh, I see. Thank you for your answer. It's very kind of you.
