### ISSUE TITLE
Questions on the valid range of FWH analogy and Dopper effect

### ISSUE THREAD

**Issue by windseacn** [unicfdlab/libAcoustics#74]
(1) I'm interested in the libacoustics code and thanks for your effort. I  am a bit confused on the valid range of FWH analogy, the two sentences below are from different ppt/papers, which is not consistent from my view:

A: The Farassat 1A Formulation provides an integral representation of the FWH equation, which does not take into consideration the quadrupole term. This assumption is valid when the flow is not in the transonic regime.

B: These codes do not include quadrupoles outside the control surface, because it was found to be of minor importance unless the Mach number is really high.

For A  the quadrupole could be neglected unless the flow is in transonic regime, which means it is valid for high Mach number flows while for B this is only valid if Mach number is not high. Can any experts help me know what's the valid range of FWH analogy?

(2) The second question is whether the Curle and FWH analogy take the Dopper effect into account?

**Comment by unicfdlab** [comment]
Hi,

current implementation of Curle in libAcoustics doesn't account for Doppler effcect. FWH is able to account for Doppler effect, however, we didn't verify it for large Mach numbers.  As far as I know, verification for high Mach numbers will require modification of solution procedure, because of complexities arising with retarded time calculation.

Since Ma number is present in the denominator part of monopole and dipole sources, FWH analogy cannot be be used for transonic flows. Therefore, I think this is a main restriction for transonic flow.

Integration of quadrupole source must involve volume integration, which is not implemented in libAcoustics.

**Comment by windseacn** [comment]
Thanks for your quick reply.
I'm still not clear whether quadrupole source should be taken into account for the supersonic regime, the libacoustics solver claims that  FWH analogy can be used "for noise prediction generated by unsteady subsonic and supersonic flows around fixed and moving obstacles or jets". It seems that quadrupole could be neglected for supersonic flows.

While from another paper, "These codes do not include quadrupoles outside the control surface, because it was found to be of minor importance unless the Mach number is really high.". It seems that quadrupole should be taken into account for high Mach number flows , e.g. supersonic flows?

**Comment by unicfdlab** [comment]
This question is more theoretical, I would recommend you to refer to special literature
